# Generated by Django 4.2.26 on 2025-12-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['nombre'], 'verbose_name': 'Programa de Formación', 'verbose_name_plural': 'Programas de Formacion'},
        ),
    ]
